### ISSUE TITLE
operationId "deleteBooking" is not unique on certain Koha branches

### ISSUE THREAD

**Issue by PerplexedTheta** [LMSCloud/LMSRoomReservations#3]
Hi @LMSCloudPaulD,

As we discussed [in this Mattermost thread](https://chat.koha-community.org/koha-community/pl/xz3nf6n5mpry3py99oe388csqw), operationId "deleteBooking" is not unique on certain custom Koha branches we use.

This seems to be because of the bookings work we're doing in core Koha. I've attached a (very) crude patch file so we don't forget what the fix was.

Thanks,
@PerplexedTheta

[diff.patch](https://github.com/user-attachments/files/15760320/diff.patch)

**Comment by LMSCloudPaulD** [comment]
See https://github.com/LMSCloud/LMSRoomReservations/releases/tag/v4.8.3-beta.12
